spring:
  application:
    name: ttopullae


  datasource:
    url: jdbc:mysql://localhost:3306/main_db
    username: root
    password: asd1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

